@echo off
echo Starting SentiPort Research Dashboard Setup...
cd research_stock_predictor
if not exist .venv (
    echo Creating virtual environment...
    python -m venv .venv
)
echo Activating environment...
call .venv\Scripts\activate
echo Installing/Updating dependencies...
pip install -r requirements.txt
echo Launching Dashboard...
streamlit run app/main.py
pause
